---
title: "Summer_prec_variability"
author: "Linda Menk"
date: "24 8 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load libraries, message = FALSE}
library(SPEI)
library(raster)
library(ncdf4)
library(terra)
library(chron)  # for the datestring  
library(rasterVis)
library(grid)
library(gridExtra)
``` 

```{r load data both, warning = FALSE, message = FALSE, echo = FALSE}
# set path and filename

prepare_data <- function(filename){
ncpath <- "R:\\02_PROJECTS\\01_P_330001\\127_UNCHAIN\\03__Work\\WP4\\03_Casestudy\\02_Data\\01_ZAMG_SPARTACUS_Monthly\\"
ncname <- filename  
ncfname <- paste(ncpath, ncname, ".nc", sep="")
dname <- "pr" #pr is the variable that holds the precipitation values

ncin <- nc_open(ncfname)
#print(ncin)

lon <- ncvar_get(ncin,"lon")
lat <- ncvar_get(ncin,"lat")

# Reading the precipitation data for the vegetation months.
# We have 575 x/lon and 297 y/lat values. 1572 is the original number of timesteps (including the whole year).
prec_array <- ncvar_get(ncin, "pr", c(1,1,1,1), c(575,297,1572,1))
nc_close(ncin)

# Creating an empty brick with 297 rows, 575 columns and 786 layers (6 vegetation months รก 131 years)
br <- brick(nrows=297, ncols=575, xmn=min(lon), xmx=max(lon), ymn=min(lat), ymx=max(lat), nl=1572, crs=4326)

# Here, the empty brick is populated with the precipitation data
br_val <- setValues (br, prec_array)
#plot(br_val)

# For some reason the values were flipped, so here we flip it back
prec_brick_flip <- flip(br_val,2)
}

RCP_45 <- prepare_data("oeks-rcp45-pr-austria-MS")
RCP_85 <- prepare_data("oeks-rcp85-pr-austria-MS")
``` 


# Variability in precipitation RCP 4.5 & RCP 8.5  
### t1 = 1981-2010  
### t2 = 2021-2050  
### t3 = 2071-2100  

```{r Calculate vaiability for Jun, fig.width=12, message = FALSE, echo = FALSE}
# Calculate variability for the month June
export_path <- "R:\\02_PROJECTS\\01_P_330001\\127_UNCHAIN\\03__Work\\WP4\\03_Casestudy\\02_Data\\01_ZAMG_SPARTACUS_Monthly\\Output\\Variability"

single_month <- function(month_x, data, m1, m2, m3, output_ref, output_t1, output_t2, rcp, month_y){
month <- month_x
jja_months <- rep ((12 * 0:130), each = length(month)) + month
jja <- subset(data, jja_months)

# To test whether the average over the reference period is 0
ref_per <- subset(jja, m1)
per_2021_2050 <- subset(jja, m2)
per_2071_2100 <- subset(jja, m3)

ref_per_sd <- calc(ref_per, sd)
ref_per_mean <- calc(ref_per, mean)
writeRaster(ref_per_sd, filename = paste0(export_path,output_ref), format="raster", overwrite=TRUE,options=c("INTERLEAVE=BAND","COMPRESS=LZW"))

per_2021_2050_sd <- calc(per_2021_2050, sd)
per_2021_2050_mean <- calc(per_2021_2050, mean)
writeRaster(per_2021_2050_sd, filename = paste0(export_path,output_t1), format="raster", overwrite=TRUE,options=c("INTERLEAVE=BAND","COMPRESS=LZW"))

per_2071_2100_sd <- calc(per_2071_2100, sd)
per_2071_2100_mean <- calc(per_2071_2100, mean)
writeRaster(per_2071_2100_sd, filename = paste0(export_path,output_t2), format="raster", overwrite=TRUE,options=c("INTERLEAVE=BAND","COMPRESS=LZW"))

delta_2021_2050 <- per_2021_2050_sd-ref_per_sd
delta_2071_2100 <- per_2071_2100_sd-ref_per_sd


rasterNames <- c("Mean t1", "Mean t2", "Mean t3")
Variation <- brick(ref_per_mean,per_2021_2050_mean, per_2071_2100_mean)
mean <- rasterVis::levelplot(Variation, main="Mean",
                     names.attr=rasterNames, 
                     scales=list(draw= FALSE),
                     layout=c(1,3), 
                     par.settings = viridisTheme())

rasterNames <- c("Standard Deviation t1", "Standard Deviation t2", "Standard Deviation t3")
Variation <- brick(ref_per_sd, per_2021_2050_sd, per_2071_2100_sd)
sd <- rasterVis::levelplot(Variation, main="Standard Deviation",
                     names.attr=rasterNames, 
                     scales=list(draw= FALSE),
                     layout=c(1,3), 
                     par.settings =PuOrTheme())

rasterNames <- c("Delta of sd in t1 minus sd in ref period", "Delta of sd in t2 minus sd in ref period")
Variation <- brick(delta_2021_2050, delta_2071_2100)

delta <- rasterVis::levelplot(Variation, main="Delta",
                     names.attr=rasterNames, 
                     scales=list(draw= FALSE),
                     layout=c(1,2), 
                     par.settings = PuOrTheme())

gridExtra::grid.arrange(mean, sd, delta, ncol=3,top=textGrob(paste(rcp, month_y)))

}

jja_45  <- single_month(6:8,RCP_45, 34:123, 154:243, 303:393, 'JJA_Variance_RCP45_1981_2010.grd','JJA_Variance_RCP45_2021_2050.grd', 'JJA_Variance_RCP45_2071_2100.grd', "RCP 4.5 ", "June-August")                       
#june_45 <- single_month(6,RCP_45, 12:41, 52:81, 102:131,"RCP 4.5", "June")
#july_45 <- single_month(7,RCP_45, 12:41, 52:81, 102:131,"RCP 4.5", "July")
#augu_45 <- single_month(8,RCP_45, 12:41, 52:81, 102:131,"RCP 4.5", "August")
jja_85  <- single_month(6:8,RCP_85, 34:123, 154:243, 303:393,'JJA_Variance_RCP85_1981_2010.grd','JJA_Variance_RCP85_2021_2050.grd', 'JJA_Variance_RCP85_2071_2100.grd', "RCP 8.5", "June-August")                       
#june_85 <- single_month(6,RCP_85, 12:41, 52:81, 102:131,"RCP 8.5", "June")
#july_85 <- single_month(7,RCP_85, 12:41, 52:81, 102:131,"RCP 8.5", "July")
#augu_85 <- single_month(8,RCP_85,12:41, 52:81, 102:131,"RCP 8.5", "August")


# To write the rasterbrick to disk


```

Calcuate SPI for single months in summer and Dec-Jan-Feb
```{r SPI, fig.width= 12, fig.height = 8, message = FALSE, echo = FALSE}

# Reference period: 1981 - 2010
# First projection: 2021 - 2050
# Second projection: 2071 - 2100

SPI_slicer <- function(filename, month_x, m1, m2, m3, rcp, month_y){
  
path <- "R:\\02_PROJECTS\\01_P_330001\\127_UNCHAIN\\03__Work\\WP4\\03_Casestudy\\02_Data\\01_ZAMG_SPARTACUS_Monthly\\Output\\Data\\"
name <- filename  
data <- paste0(path, name)
brick <- brick(data) 

month <- month_x
range <- rep ((12 * 0:130), each = length(month)) + month
SPI_subset <- subset(brick, range)

SPI_ref_period <- subset(SPI_subset, m1)
SPI_2021_2050 <- subset(SPI_subset, m2)
SPI_2071_2100 <- subset(SPI_subset, m3)

# Count the number of cells with a value <=-1 in each cell stack
count_1981_2010 <- calc(SPI_ref_period, fun=function(x){
  sum(x <= -1)
})
count_1981_2010 <- count_1981_2010/30


# For middle of the century
count_2021_2050 <- calc(SPI_2021_2050, fun=function(x){
  sum(x <= -1)
})
count_2021_2050 <- count_2021_2050/30


# For end of the century
count_2071_2100 <- calc(SPI_2071_2100, fun=function(x){
  sum(x <= -1)
})
count_2071_2100 <- count_2071_2100/30

# Calculate delta 
delta_2021_2050 <- count_2021_2050 - count_1981_2010
delta_2071_2100 <- count_2071_2100 - count_1981_2010


# Plot the three time slices
rasterNames <- c("1981-2010", "2021-2050", "2071-2100")
prec_count <- brick(count_1981_2010, count_2021_2050, count_2071_2100)
count <- levelplot(prec_count, main=paste("Months with SPI <= -1 \nfor", rcp, month_y),
                     names.attr=rasterNames, 
                     scales=list(draw= FALSE),
                     layout=c(1,3),
                     par.settings = YlOrRdTheme())
# Plot delta
rasterNames <- c("2021-2050", "2071-2100")
prec_delta <- brick(delta_2021_2050, delta_2071_2100)
delta <- levelplot(prec_delta, main=paste("Delta SPI <= -1 (t1/2 minus ref period)", rcp, month_y),
                     names.attr=rasterNames, 
                     scales=list(draw= FALSE),
                     layout=c(1,2), 
                     par.settings = BuRdTheme())

gridExtra::grid.arrange(count, delta, ncol=2,top=textGrob(paste(rcp, month_y)))

}


SPI_June_RCP45 <- SPI_slicer("SPI_AustriaRCP_45ts1.grd", 6, 12:41, 52:81, 102:131, "RCP 4.5 / SPI-1", "June")
SPI_July_RCP45 <- SPI_slicer("SPI_AustriaRCP_45ts1.grd", 7, 12:41, 52:81, 102:131, "RCP 4.5 / SPI-1", "July")
SPI_Aug_RCP45 <- SPI_slicer("SPI_AustriaRCP_45ts1.grd", 8, 12:41, 52:81, 102:131, "RCP 4.5 / SPI-1", "August")
SPI_June_RCP85 <- SPI_slicer("SPI_AustriaRCP_85ts1.grd", 6, 12:41, 52:81, 102:131, "RCP 8.5 / SPI-1", "June")
SPI_July_RCP85 <- SPI_slicer("SPI_AustriaRCP_85ts1.grd", 7, 12:41, 52:81, 102:131, "RCP 8.5 / SPI-3", "July")
SPI_Aug_RCP85 <- SPI_slicer("SPI_AustriaRCP_85ts1.grd", 8, 12:41, 52:81, 102:131, "RCP 8.5 / SPI-1", "August")

SPI_DJF_RCP45 <- SPI_slicer("SPI_Austria_RCP45.grd", 2, 12:41, 52:81, 102:131, "RCP 4.5 / SPI-3", "February")
SPI_DJF_RCP85 <- SPI_slicer("SPI_Austria_RCP85.grd", 2, 12:41, 52:81, 102:131, "RCP 8.5 / SPI-3", "February")

# writeRaster(count_1981_2010_45, "SPI_count_1981_2010_45_RCP45.tif", format = "GTiff", overwrite = TRUE)
# writeRaster(count_2010_2021_45, "SPI_count_2010_2021_45_RCP45.tif", format = "GTiff", overwrite = TRUE)
# writeRaster(count_2071_2100_45, "SPI_count_2070_2100_RCP45.tif", format = "GTiff", overwrite = TRUE)
# 
# writeRaster(delta_2021_2050_45, "SPI_delta_2021_2050_RCP45.tif", format = "GTiff", overwrite = TRUE)
# writeRaster(delta_2071_2100_45, "SPI_delta_2070_2100_RCP45.tif", format = "GTiff", overwrite = TRUE)
```

